
exports.zhLocaleMessage = {
  'linkSuccessfully': '绑定成功',
  'linkFailed': '绑定失败',
  'unlinked': '未绑定',
  'unSend': '未赠送',
  'hasLinked': '已绑定成功',
  'buySuccessfully': '购买成功',
  'waitFriendsToLinkCard': '等待好友绑定卡片',
  'give': '赠送',
  'buy': '购买',
  'giftForSelf': '送给自己的礼物',
  'physicalGiftCard': '实体礼品卡',
  'physicalGiftCardLinked': '绑定的实体卡',
  'youFromStar': '来自星星的你',
  'isTheFirstDayWeKnowEachOther': '是我们认识的第一天',
  'nearestxx': '最近的 {name} {desc}',
  'xxAwayFromMe': '距离我{amount}',
  'giftFromxx': '来自{name}的赠送',
  'xxHasReceivedYourGift': '好友{name}已收到你的心意',
  'availablexxDays': '有效期: {amount}天',
  'availablexxDaysPureText': '有效期{amount}天',
  'activiyEndAtxx': '活动于{date}结束',
  'selectedxxCount': '已选中{amount}件',
  'getxxRMB': '获得{amount}元',
  'unlinkTipsContent': '解绑后，你的会员账号将会与商家在{name}平台中的所有产品解绑',
  'xxGiftCardLinked': '已绑定{amount}张礼品卡',
  'birthdayPopupContent': '填写生日即可获得{name}在您生日时为您提供的生日礼',
  'xxShopsAvailable': '共{amount}家门店可用',
  'totalxxShops': '共{amount}家门店',
  'promoteToEarnxxRMB': '推广赚¥{amount}',
  'acceptGiftCardDialogDesc': '{userName}送你一张价值{amount}元的{giftCardName}礼品卡，卡内包含{packageName}套餐和Ta想对你说的悄悄',
  'thisEventWillEndAtxx': '本期活动将于{date}结束',
  'referRuleItem1': '1 参与用户: 所有{name}会员都可参加',
  'referRuleItem2': '2 活动时间: {start} 至 {end}',
  'referRuleItem3': '3 好友奖励: 活动期间将活动发送给被推荐者，被推荐者打开链接，即可获得奖励',
  'referRuleItem4': '4 我的奖励: 活动期间将活动发送给被推荐者，被推荐者到店使用奖励优惠券后，我可获得奖励',
  'referRuleItem5': '5 奖励使用规则: 代金券可累计使用',
  'referRuleItem6': '6 活动最终解释权归{name}所有',
  'conditionForRedPocketText': '24小时内召唤{amount}位好友开超大现金红包',
  'actionForRedPocket': '24小时内召唤{amount}位好友',
  'yourFriendInviteYou': '你的好友{name}邀请你',
  'redEnDoneTipsText': '终于集齐{amount}位好友，可以一起开红包了',
  'appointRuleItem1': '1 参与用户: 所有{name}会员都可参加',
  'appointRuleItem2': '2 活动时间: {start} 至 {end}',
  'appointRuleItem3': '3 活动流程：用户点击【发起约饭】后即可将连接发送至微信好友或微信群，集齐好友后，发起者即可获得奖励',
  'appointRuleItem4': '4 同一时间发起者只可以发起一场约饭活动',
  'appointRuleItem5': '5 活动最终解释权归{name}所有',
  'tierPageMemberDesc': '已绑定 {amount} 位团员',
  'tierMemberMesage': '已成功绑定 {amount} 位团员',
  'tierScrollingMessageContent': '{name} 刚刚推广成功, 获得{amount}元奖励',
  'containsxxCoupons': '内含{amount}张优惠券',
  'giftCardOnePieceContent': '包含以下{amount}件商品，原价{originalPrice}元，已优惠{deductPrice}元',
  'xxPoints': '{amount}积分',
  'xxPrepay': '{amount}元储值',
  'xxOfxxMember': '{bgName}{levelTitle}会员',
  'tierRewardFromxxReward': '来自{name}的返佣奖励',
  'xxToAccount': '{date}到账',
  'signInfor': '连续签到',
  'signInToGift': '天送好礼',
  'hadSignIn': '已连续签到{day}天',
  'signInConsToGift': '连续签到{day}天可领取',
  'availablexxToxx': '有效期: {name}',
  'moreCodeMoreRate': '抽奖码越多，中奖概率越高',
  'marketPrice': '市场价',
  'getLuckyCode': '获得一张奖券码',
  'lotteryGameOver': '活动已过期啦～',
  'myLuckyCode': '我的抽奖码',
  'lotteryWinedAt': '中奖时间',
  'lotteryRedeem': '确认兑换',
  'lotteryRedeemed': '已兑换',
  'lotteryNoRecord': '你还没有中奖记录',
  'lotteryGoDraw': '快去试试手气吧～',
  'lotteryCode': '兑换码',
  'lotteryGoRecord': '查看奖励',
  'lotteryMissLucky': '差一点点就中奖啦～',
  'lotteryCongratulations': '恭喜你，中奖啦',
  'lotteryCallUs': '联系商家',
  'lotteryPrizeHad': '奖励已自动放入我的资产',
  'activityRules': '活动规则',
  'iUnderstand': '朕知道了',
  'loading': '加载中',
  'lotteryUnit': '张',
  'activityOfflineAt': '距离活动结束还有{day}天',
}

exports.enLocaleMessage = {
  'lotteryUnit': ' ',
  'loading': 'Loading',
  'iUnderstand': 'I understand',
  'activityRules': 'Rules',
  'lotteryGoRecord': 'View rewards',
  'lotteryMissLucky': 'You are so close to win',
  'lotteryCongratulations': 'Congratulations, you win',
  'lotteryCallUs': 'Contact us',
  'lotteryPrizeHad': 'The balance has been transferred to my property',
  'lotteryCode': 'Redeem code',
  'lotteryRedeem': 'Redeem',
  'lotteryRedeemed': 'Redeemed',
  'lotteryNoRecord': 'There is no winning record,',
  'lotteryGoDraw': 'go and draw a lottery',
  'lotteryWinedAt': 'The winning time',
  'lotteryGameOver': 'The activity is finished',
  'myLuckyCode': 'My lucky draw code',
  'moreCodeMoreRate': 'More draw code , higher win rate',
  'marketPrice': 'Market price',
  'linkSuccessfully': 'Link successfully',
  'linkFailed': 'Link failed',
  'unlinked': 'unlinked',
  'unSend': 'Not given',
  'hasLinked': 'Linked successfully',
  'buySuccessfully': 'Successfully purchase',
  'waitFriendsToLinkCard': 'Waiting for friends to bind cards',
  'give': 'Give',
  'buy': 'Buy',
  'giftForSelf': 'Gift for myself',
  'physicalGiftCard': 'Physical gift card',
  'physicalGiftCardLinked': 'Linked physical gift card',
  'youFromStar': 'You from the star',
  'isTheFirstDayWeKnowEachOther': ' is the first day we know each other',
  'nearestxx': 'The nearest {name} shop is {desc}',
  'xxAwayFromMe': '{amount} away from me',
  'giftFromxx': 'Gift from {name}',
  'xxHasReceivedYourGift': 'Your friend {name} has received your gift',
  'availablexxDays': 'Validity: {amount} days',
  'availablexxDaysPureText': 'Valid for {amount} days',
  'activiyEndAtxx': 'The activity ends on {date}',
  'selectedxxCount': '{amount} selected',
  'getxxRMB': 'Get ¥{amount}',
  'unlinkTipsContent': 'Once unlinked, your member account will be unlinked with all products on the {name} platform',
  'xxGiftCardLinked': '{amount} gift card linked',
  'birthdayPopupContent': 'Fill in your birthday to get a birthday gift for you on your birthday',
  'xxShopsAvailable': '{amount} shops available',
  'totalxxShops': '{amount} shops in total',
  'promoteToEarnxxRMB': 'Earn ¥{amount}',
  'acceptGiftCardDialogDesc': '{userName} sends you a {giftCardName} gift card worth ¥{amount}, which contains {packageName} packages and the words he/she wants to say to you',
  'thisEventWillEndAtxx': 'This event will end on {date}',
  'referRuleItem1': '1 Participant: All members of {name}',
  'referRuleItem2': '2 Promotion time: {start} - {end}',
  'referRuleItem3': '3 Reward for friends: Send the event to the friend during the event, and the friend opens the link to receive the reward',
  'referRuleItem4': '4 My reward: Send the event to the friend during the event, and I get a reward when the friend used the reward coupon at the store',
  'referRuleItem5': '5 Reward usage rules: Vouchers can be used cumulatively',
  'referRuleItem6': '6 The final interpretation of the event is owned by {name}',
  'conditionForRedPocketText': 'Call {amount} friends to open oversized cash red envelopes in 24 hours',
  'actionForRedPocket': 'Call {amount} friends in 24 hours',
  'yourFriendInviteYou': 'Your friend {name} invite you',
  'redEnDoneTipsText': 'Finally gathered {amount} friends, you can open a red envelope together',
  'appointRuleItem1': '1 Participant: All members of {name}',
  'appointRuleItem2': '2 Promotion time: {start} - {end}',
  'appointRuleItem3': '3 Activity process: Users can click on the "Launch" to send the link to WeChat friends or WeChat group, after all friends joined, the promoter can be rewarded',
  'appointRuleItem4': '4 Sponsors can only initiate an event at the same time',
  'appointRuleItem5': '5 The final interpretation of the event is owned by {name}',
  'tierPageMemberDesc': '{amount} members linked',
  'tierMemberMesage': '{amount} members linked successfully',
  'tierScrollingMessageContent': '{name} just promoted success, won an ¥{amount} reward',
  'containsxxCoupons': 'Include {amount} coupons',
  'giftCardOnePieceContent': 'Contains the following {amount} items, the original price of ¥{originalPrice}, has been discounted ¥{deductPrice}',
  'xxPoints': '{amount} Points',
  'xxPrepay': '¥{amount} balance',
  'xxOfxxMember': 'The {bgName} {levelTitle} member',
  'tierRewardFromxxReward': 'Rebate rewards from {name}',
  'xxToAccount': '{date} account',
  'signInfor': 'Sign in for',
  'signInToGift': 'consecutive days to get gifts',
  'hadSignIn': 'You have signed in for {day} consecutive days',
  'signInConsToGift': 'Sign in for consecutive {day} days to get gift',
  'availablexxToxx': 'Expiration date: {name}',
  'activityOfflineAt': '{day} days from the end of the event',
}
