module.exports = {
  'selectLanguage': 'Select Language',
  'confirm': 'Confirm',
  'noGiftcardTips': 'Merchants haven\'t released any cards yet.',
  'giftcardPack': 'Fixed Card',
  'sendGiftCardAsPresent': 'Send gift card as present',
  'buySuccessfully': 'Successfully purchase',
  'fixedCard': 'Fixed Card',
  'freeRide': 'Free Ride', // ?
  'sentSuccessfully': 'Sent successfully',
  'homepage': 'My Homepage', // ?
  'iWantBuyCard': 'I want to buy a card too',
  'claimFailed': 'Claim failed',
  'reciveSuccessfully': 'Receive Successfully',
  'giftYouACard': 'Gift you a card',
  'getGiftCard': 'Get gift card',
  'sendGiftcardTips': 'Your heart has been sent to a friend, and your friend can use the card once it is bound', // ?
  'goCheck': 'Go check',
  // 包
  // 品
  // 套餐
  // 礼品
  // 一份
  // 包
  'buyNow': 'Buy now',
  'prepay': 'Balance', // ?
  // 固定卡
  // 随心搭
  'paidFailed': 'Payment failed',
  'paidSuccessfully': 'Paid successfully',
  'giftCardMall': 'Gift card mall',
  'loading': 'Loading',
  'allGiftcard': 'All gift cards',
  'allCombocard': 'All combo cards',
  'buyGiftcard': 'Buy gift card',
  'purchasedGiftcard': 'Purchased gift card',
  'giftCard': 'Gift card',
  'joinUsForGiftcard1': 'must be a member to view gift card details', // ？
  'joinUsForGiftcard2': 'must be a member to see more gift cards', // ？
  'freeComboCard': 'Free ride', // ？
  'giftcardEmptyTips1': 'You haven\'t purchased a gift card yet',
  'giftcardEmptyTips2': ' you have not purchased a gift card',
  'giftcardEmptyTips3': 'Not yet link gift cards, you can:', // ?
  'goBuyGiftcard': 'Buy gift card',
  'goShopBuyGiftcard': 'Go to the store to buy a physical card', // ?
  'bindPhysicalCard': 'Link physical card',
  'buyDigitalCard': 'Buy electronic card',
  'noMore': 'No more', // ?
  'giveCardDesc': 'Tips', // ？
  'giftcardSoldOut': 'Merchants don\'t have gift cards on sale for the time being Oh, you can also：',
  'viewPurchaseHistory': 'View the purchase history', // ?
  'giftcardTaken': 'Come on, the gift card has been taken away', // ？
  'moreFood': 'more food', // ?
  'registerTips': 'You are not yet a member, please register to sign in', // ？
  'thankYouTips': 'Thank you for having you, send you a full heart', // ?
  'getItNow': 'Get it right now',
  'congratForGetting': 'Congratulations on getting ',
  'seeMoreFoodOnHomepage': ' See more food on the homepage',
  'enterCardNum': 'Please enter the card number',
  'enterCardPass': 'Please enter the card password',
  'confirmBind': 'Confirm to link',
  'enterBarcode': ' Please scan the correct barcode',
  'cardNumNoEmpty': 'Card number and password cannot be empty!',
  'scanFail': 'Scanning failed',
  'linkSuccessfully': 'Linked successfully',
  'bindFail': 'Linking card failed',
  'unlinkedCard': 'Unlinked Card',
  'buyHistory': 'Purchase history',
  'payIn': 'Pay in', // ?
  'sendCardTips': 'Send you a gift card and hope you eat well and drink everything is fine.', // ?
  'physicalCard': 'Physical card',
  'digitalCard': 'Electronic card',
  'personalCenter': 'Personal center',
  'sendCardTips2': 'Please select the card you want to give/link', // ？
  'returningCommissionDetail': 'Details',
  'totalEarn': 'Returned commission in total',
  'promotePath': 'Promotion solution',
  'allPromotionRules': 'All promotion rules',
  'promoteItem': 'Selected promotion item',
  'promote': 'Promote',
  'promoteTips': 'More promotions more rewards', // ?
  'viewed': 'All the content is above',
  'promotionEmpty': 'Shop has not set item',
  'viewOthers': 'Go and view other pages',
  'promotionRule': 'Promotion rules',
  'promotionRules1': 'If the inviter successfully invites friend A to join the club，the inviter become the leader',
  'promotionRules2': 'If the leader shares the mini-program with friend A and friend A become membership, the leader will be uniquely bound to friend A',
  'promotionRules3': 'After the leader is bound with friend A, any purchase made by friend A on the promotional money-making page can help the leader get returned commission reward',
  'promotionRules4': 'The leader can enter the promotion page through the promotional money-making entrance on [Home] or [My] page',
  'promotionRules5': 'Select the promote product in the promotional money-making page, tap promote to earn XX yuan',
  'promotionRules6': 'Share links or posters of promoted products to friends / circle of friends',
  'promotionRules7': 'Friends tap the  link or long press the poster QR code to enter the promoted product detail page and purchase the product',
  'promotionRules8': 'The leader can get the corresponding reward',
  'promotionRules9': 'Reward distribution',
  'promotionRules10': 'Product rewards are based on what is displayed on the page',
  'promotionRules11': 'The leader successfully invites friend A to place an order, and the returned commission reward will be automatically distributed to the merchant\'s mini-program [My-Balance]. The returned commission reward can only be used in shop or deduction during takeaway consumption',
  'promotionRules12': 'Goods purchased by friend A can be viewed in the merchant mini-program [My-Coupon]',
  'promotionRules13': 'The final interpretation of the promotion belongs to the merchant',
  'tap': 'Tap', // ?
  'allPromoteItem': 'All promotion item',
  'selectPromoteItem': 'Select all promotion item',
  'sharePromoteItem': 'Share links/posters to friends',
  'openPromoteItem': 'Friends placing an order via link/poster',
  'getMoney': 'Leader receives rebate reward',
  'expectEarn': 'Expected earnings', // ?
  'promoteProducts': 'Promotion products', // ?
  'promoteToFriends': 'Promote',
  'savePoster': 'Save poster',
  'getSavePicAuth': 'To authorize the album', // ？
  'getSavePicAuthTips1': 'You don\'t have permission to save pictures to albums, so you can\'t save pictures, you can open the authorization according to the following', // ?
  'getSavePicAuthTips2': 'Click on the top right corner of the page', // ?
  'getSavePicAuthTips3': 'In Select Settings, go to the settings page', // ?
  'getSavePicAuthTips4': 'Turn on album authorization', // ?
  'recommendCoupon': ' recommend you a value coupon', // ？
  'superCheap': 'Discount',
  'recommendCoupon2': 'Highly recommend it to you', // ?
  'superCheap2': 'Things',
  'recommendCoupon3': ' recommend you a good thing', // ？
  'posterLoading': 'Poster loading',
  'saveFail': 'Save failed',
  'posterTips1': 'Long-press picture Identify QR code Buy Now', // ?
  'teamMember': 'My team member',
  'noMember': 'You don\'t have any team member',
  'memberTips1': 'Go to promote items and recruit member',
  'memberTips2': 'Returned commission in total is', // ?
  'memberTips3': 'You haven\'t returned the message yet.', // ?
  'memberTips4': 'Go and promote the merchandise to make money', // ?
  'couponContent': 'Content',
  'dishUnit': 'dish',
  'noticeForUse': 'Notice for use',
  'applicableStores': 'Applicable stores',
  'allApplicableStores': 'All applicable stores',
  'productDetail': 'Product details',
  'productExpired': 'This item is expired',
  'productOffline': 'This item is offline， go and view other items',
  'viewItemList': 'Go to item list',
  'viewHompage': 'Go to homepage',
  'becomeMember': 'Become a member',
  'cancelTips': 'Canceled successfully，please retry to purchase',
  'reBuy': 'Retry to purchase',
  'couponDelay': 'Coupon delay remind',
  'couponDelayTips': 'Your coupon is stuck in a traffic jam，please wait a moment，it is coming~ (if it isn’t to account in 5 minutes, please contact shop in item detail page)',
  'networkDown': 'No internet service',
  'networkDownTips1': 'Lose network service，please refresh to retry',
  'networkDownTips2': 'Refresh to retry',
  'couponsTips1': 'Coupons have been placed in my coupons, please go to the store as soon as possible to use it', // ?
  'couponsTips2': 'View my coupon',
  'buyFailed': 'Purchase unsuccessfully',
  'buyFailedTips': 'The amount you paid will be returned to your payment account in the same way within 1-3 days',

  // theme activity
  'activitiesIJoin': 'Activities I\'m involved in', // ?
  'noActivity': 'No activity', // ?
  'beMemberToJoinActivities': 'You can participante after becoming membership',
  'viewDetail': 'View',
  'joinToGetCouponText1': 'Join a merchant member and receive a coupon', // ?
  'joinToGetCouponText2': 'As soon as you type, pick up the coupon', // ?
  'couponUseWay': 'When you shop, report your phone number to the waiter.', // ?
  'moreActivities': 'More activities',
  'couponRecieve': 'Rewards have been automatically placed in my-coupon',
  'couponForNewMember': 'This offer is only available to new people',
  'shareToFriendsGetReward': 'Recommended to friends to get rewards', // ?
  'shareToFriends': 'Recommend friends now', // ?
  'viewMoreActivities': 'See more activities',
  'activityOver': 'This activity is over', // ?
  'viewOtherActivity': 'Go see other activities',
  'viewOtherActivity2': 'Go see other activities.',
  'redEnvelopeInstruction': 'Red envelope instructions', // ?
  'promotionDetail': 'Promotion details', // ?
  'friendReferralPlan': 'Friend Referral Plan',
  'unknownError': 'Unknown error',
  'activityRules': 'Rules',
  'myReward': 'My reward',
  'friendsAvailable': 'Friends available', // ?
  'threeStepTips1': 'Simple three-step offer', // ?
  'threeStepTips2': 'Recommend activities to friends', // ?
  'threeStepTips3': 'Friends open links and shop', // ?
  'threeStepTips4': 'Recommended success to get reward', // ?
  'moneyComingSoon': 'Coming soon',
  'earnedCumulative': 'Earned cumulative',
  'myRecommendationRecord': 'My recommendation record', // ?
  'noShareYet': 'You don\'t have any refer yet', // ?
  'error': 'Error',
  'backHome': 'Back to home',
  'referFriendsTips': 'I love this restaurant so much that I must share it with you. I\'ll give you another great gift',
  'invitationSuccessfully': 'Invitation successful',
  'gatherNow': 'Call together now',
  'friendsJoined': 'Friends who have been successfully called', // ?
  'joinNow': 'Join now',
  'tipsMessage': 'Tips',
  'backMainPage': 'Back to home',
  'joinSuccessfully': 'Join successfully',
  'reopenActivity': 'Relaunch promotions',
  'rewardDetails': 'Reward details',
  'attendNow': 'Join now',
  'inviteFriends': 'Invite Friends',
  'openRedEnvelope1': 'Together to tear down the cash red envelope', // ?
  'openRedEnvelope2': 'Join us to get money',
  'openRedEnvelope3': 'You can open an oversized cash red envelope', // ?
  'startActivity': 'Launch promotions',
  'eatWithFriends': 'Let\'s dine with your friends.',
  'rewardsAtMineCoupon': 'Rewards are automatically placed in my-coupons',
  'promotionOffline': 'Promotion is offline',
  'activityNotFound': 'Non-existent theme activities',
  'invitationStarted': 'Meal invitation is sent successfully', // ?
  'warmTips': 'Tips',
  'warmReminder': 'Tips',
  'registeredToStartInvitation': 'You must be a registered user before you can send a meal invitation',
  'inviteOthersAndEat': 'Come and send a meal invitaion',
  'shareSuccessfully': 'Sharing success',
  'helpFriendsGetBenefit': 'Help friends get benefits',
  'friends': 'Peer friends', // ?
  'acceptInvitation': 'Accept invitation',
  'invitationNotFound': 'It\'s late, the dinner has already begun.', // ?
  'viewOtherInvitation': 'Discover other promotions',
  'teamMade': 'Group Office Complete', // ?
  'acceptedInvitation': 'Invitation accepted',
  'invitationEnded': 'It\'s late, the dinner is over', // ?
  'joinNextTime': 'Play next time', // ?
  'activityNotFound2': 'Non-existing activity',
  'registerAndJoin1': 'You can participate after authorization',
  'registerAndJoin2': 'You can participante after becoming membership',
  'acceptedInvitation': 'Accept invitation successfully',
  'savePicture': 'Want to save the picture',
  'activityEnded': 'This event has ended', // ?
  'activityRules1': 'Activity process', // ?
  'activityRules2': 'Click button to launch the campaign', // ?
  'activityRules3': 'Choose to send to WeChat friends or groups',
  'activityRules4': 'Gather friends to get coupon rewards',
  'myMealInvitationRecord': 'My meal invitation record',
  'startAMealInvitation': 'No appointment meal, hurry up to make an appointment',
  'coupon': 'Coupon',
  'noPromotion': 'No activated promotion in the shop',
  'shopPromotion': 'Shop promotion',
  'allShopPromotion': 'All shop promotion',
  'owner': 'Sponsor',
  'rewardsAtMineBalance': 'Rewards put in "My-Balance"',
  'startMealInvitation': 'Send invitation to meal',

  'addPoints': 'Add points',
  'usePoints': 'Deduct point',
  'deductBalance': 'Deduct balance',
  'deductReturn': 'Balance return',
  'topUpBalance': 'Top up balance',
  'unknownCard': 'Unknow card',
  'finished': 'Finished',
  'expired': 'Expired',
  'allStores': 'all shop',
  'iWantToTopUp': 'I want to top up balance', // ?
  'balanceDetail': 'Balance detail', // ?
  'totalPrepayBalance': 'Total balance', // ?
  'prepayHistory': 'Record',
  'orderHistory': 'Order history',
  'points': 'Points',
  'noItem': 'Currently no item',
  'redeemNow': 'Redeem',
  'buyAtShop': 'Buy at store',
  'pointsHistory': 'Record',
  'zmall': 'Point mall',
  'goZmall': 'Go to point mall',
  'getPointsChannelText': 'Points can be earned through merchant gifts, top up balance, and consumption', // ?
  'pointsRule': 'Points rule',
  'howToRechargeTips': 'Please select the top-up activity, and then find a waiter to top up', // ?
  'emptyPrepay': 'Currently no item',
  'toRegister': 'Go to register',
  'rechargeMustAfterRegister': 'You can top up after registration',
  'prepayCard': 'Prepay card', // ?
  'sendAfterRecharge': 'Prepay and send it later', // ?
  'limitsOfUse': 'Limits of use',
  'giveAwayOffers': 'Give away offters', // ?
  'rechargeNow': 'Top up now',
  'rechargeSuccessfully': 'To up successfully',
  'rechargeFailed': 'Top up failed',
  'rechargeFailDialogContent': 'Cancelled, please try again',
  'rechargeFailDialogContent2': 'Please retyr to top up again',
  'retryToRecharge': 'Retry to top up',
  'viewMyBalance': 'View my balance',
  'updatePassword': 'Update password',
  'savePassword': 'Save password',
  'retryPasswordPlaceholder': 'Please re-enter your password',
  'inputPasswordPlaceholder': 'Please enter a 6-digit password',
  'inputPassword': 'Please enter your password',
  'inconsistencyPassword': 'Inconsistent password',
  'enterSixDigitsOnly': 'Enter 6 digits only',
  'setUpSuccessfully': 'Set up successfully ',
  'toUse': 'Use',
  'view': 'View',
  'usable': 'Usable',
  'unavailable': 'Unavailable',
  'expired': 'Expired',
  'used': 'Used',
  'useImmediately': 'Use immediately',
  'failedReasonExpired': 'Failed reason: Expiration not used', // ?
  'noCoupons': 'No coupons',
  'useCouponCode': 'Use coupon code',
  'useCouponManual': 'use code manually', // ？
  'selectRightStore': 'Select the right shop', // ?
  'useStore': 'Use shop', // ?
  'useCouponCount': 'Use count', // ?
  'couponUnit': '',
  'verifyCodePlaceholder': 'Please ask the service staff for coupon code',
  'confirmToUseCoupon': 'Confirm to use coupon',
  'redeemCouponTips': 'Please show the serviceman the sales voucher code, sweep the code ticket', // ?
  'redeemCouponSuccessfully': 'Use coupon successfully',
  'redeemCouponFailed': 'Use coupon failed',
  'retryToRedeemCoupon': 'Retry to use coupon',
  'notSupportUseCouponManuallyTips': 'This store does not support manual coupons, please switch coupon methodor or consulting service', // ?
  'redeemCouponTip': 'Once used non-refundable, please confirm with the waiter after using this coupon', // ?
  'pleaseEnterTheCorrectCouponCode': 'Please enter the correct coupon code',
  'levelChangeRecord': 'Level change record',
  'currentLevel': 'Current level',
  'giftsAfterUpgrade': 'Level upgrade gifts',
  'giftsAfterUpgradeTip': 'Put in My Coupon/Point',
  'levelDescription': 'Level description',
  'iUnderstand': 'I understand',
  'anonymousUser': 'Anonymous user',
  'anonymous': 'Anonymous',
  'groupTriggerTypePaymentTimes': 'The number of consumption times',
  'groupTriggerTypePaymentTimesUnit': 'times',
  'groupTriggerTypeLifePoint': 'points',
  'groupTriggerTypeLifePointUnit': ' ',
  'groupTriggerTypePrepayAmount': 'balance',
  'groupTriggerTypePrepayAmountUnit': 'RMB',
  'upgradeRule': 'Upgrade rules',
  'downgradeRule': 'Downgrade rules',
  'noContent': 'None',
  'levelChangeNotice': 'Member level change notice',
  'prevLevel': 'Original level',
  'currentLevel': 'Current level',
  'noLevelChangeRecord': 'You don\'t have a level change record yet',
  'levelUp': 'Level up',
  'levelDown': 'Level down',
  'sentSuccessfully': 'sentSuccessfully',
  'pleaseEnterVerificationCode': 'Please fill in the verification code',
  'alipay': 'Alipay',
  'wechat': 'Wechat',
  'unbind': 'UnLink',
  'accountSetting': 'Account settings',
  'bindWechatSetting': 'Link wechat',
  'bindAlipaySetting': 'Link alipay',
  'passwordSetting': 'Password setting',
  'prepayPasswordSetting': 'Balance transaction password',
  'modify': 'Modify',
  'notSet': 'Not set',
  'resend': 'Resend',
  'sendVerificationCode': 'Send the verification code',
  'enterVerificationCode': 'Enter verification code',
  'reenterVerificationCode': 'Re-enter the verification code',
  'unbindAllMiniprogram': 'Unlink all',
  'confirmToUnbindAllMiniprogram': 'Unlink all mini-programs?',
  'confirmToUnbind': 'Confirm to unlink',
  'save': 'Save',
  'tips': 'Tips',
  'noAreaSelectedTips': 'Please select at least one area',
  'selectedAreaExceedLimitTips': 'Good people walk the Quartet, but still choose your most frequent 5 business districts', // ?
  'modifySuccessfully': 'Modify successfully',
  'changeCityTips': 'After changing the city, you need to re-select the business district. Are you sure you want to change the city?',
  'confirm': 'Confirm',
  'cancel': 'Cancel',
  'inputNicknamePlaceholder': 'Please enter a new nickname',
  'saveSuccessfully': 'Save successfully',
  'inputPhonePlaceholder': 'Enter phone number',
  'confirmToModify': 'Confirm the changes',
  'errorVerificationCodeTips': 'Please enter correct verification code',
  'illegalInputedPhone': 'Illegal inputed phone number',
  'cannotUseOriginalPhone': 'Cannot use original phone number',
  'scanProfileCodeTips': 'Please show the membership code to the waiter  \n to scan code to check-in or use the points',
  'memberCodeSignIn': 'Member check-in',
  'member': 'member', // ?
  'noRecord': 'No corresponding record',
  'selectAssetType': 'Select asset type',
  'nickName': 'Nickname',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Famale',
  'birthday': 'Birthday',
  'editBirthday': 'Edit birthday',
  'phoneNumber': 'Phone number',
  'editResidentCity': 'Edit resident city',
  'city': 'City',
  'businessArea': 'Business districts',
  'occupation': 'Occupation',
  'myOccupation': 'My occupation',
  'editNearbyBusinessArea': 'Edit nearby business districts',
  'pleaseSelectACityFirst': 'Please select a city first',
  'selectBusinessAreaBeforeCitySelectedTips': 'Please set up your city before you can select a business district',
  'enterBirtydayAfterTodayTips': 'Birthday cannot be later than today',
  'avatar': 'Avatar',
  'historyRecord': 'History record',
  'myGiftCard': 'My gift card',
  'linkNewCard': 'Link new card',
  'thisIsFreeGiftCard': 'This is a free gift card',
  'noGiftCardTips': 'You don\'t have a gift card yet~',
  'memberBenefits': 'Benefits',
  'moreBenefits': 'More benefits',
  'welcomesYou': 'welcome you',
  'memberScanCodeToSignIn': 'Sign in',
  'myMemberCode': 'My membership code',
  'dailySignin': 'Daily sign in',
  'personalInfo': 'Profile',
  'assetUseRecord': 'Property use record',
  'luckyRecord': 'Lucky record',
  'settings': 'Settings',
  'storehome': 'Store home',
  'my': 'Me',
  'fillInYourBirthday': 'Fill in your birthday',
  'goToFill': 'Go to fill',
  'fillInLater': 'Fill in later',
  'shopNews': 'Shop news',
  'goSignIn': 'Go sign in',
  'seeMore': 'View more',
  'seeMoreShop': 'View more',
  'entryTakeawayName': 'Delivery',
  'entryTakeawayIntro': 'Get food by touchless delivery',
  'entryTakeawayIntroBubble': 'Get food by delivery',
  'entryTakeawayLinkText': 'Order now',
  'entryHuipayName': 'Pay',
  'entryHuipayIntro': 'Discount pay',
  'entryHuipayLinkText': 'Pay now',
  'entryZmallName': 'Point mall',
  'entryZmallIntro': 'Redeem gift',
  'entryZmallLinkText': 'Enter',
  'entryPrepayName': 'Top up',
  'entryPrepayIntro': 'Save more, send more',
  'entryPrepayLinkText': 'Enter',
  'entryGiftCardName': 'Gift card',
  'entryGiftCardIntro': 'Exclusive discount',
  'entryGiftCardLinkText': 'Enter',
  'entryActivityName': 'Promotion',
  'entryActivityIntro': 'Get involved to win reward',
  'entryActivityLinkText': 'Enter',
  'entryAdvertorialName': 'News',
  'entryAdvertorialIntro': 'Redeem discount',
  'entryAdvertorialLinkText': 'Enter',
  'entryTierName': 'Promote',
  'entryTierIntro': 'Get reward',
  'entryTierIntroBubble': 'Get reward',
  'entryTierLinkText': 'Enter',
  'mainEntryAddress': 'Address',
  'mainEntryRecommendDishes': 'Recommendations',
  'mainEntryHuipay': 'Discount pay',
  'mainEntryZmall': 'Point mall',
  'mainEntryPrepay': 'Top up',
  'mainEntryGiftCard': 'Gift card',
  'mainEntryMembershipCode': 'Membership code',
  'mainEntryAdvertorial': 'News',
  'mainEntryAdvertorialSuffix': '',
  'mainEntryActivity': 'Activities',
  'mainEntryTakeaway': 'Takeaway',
  'mainEntryTier': 'Promote',
  'allShops': 'All shop',
  'nearestShop': 'The nearest shop',
  'shopsNearMe': 'Shops near me',
  'recommendDishesTitle': 'Recommendations',
  'recommendDishesTitleSuffix': '',
  'allRecommendDishes': 'All',
  'linked': 'Linked',
  'unlinked': 'UnLinked',
  'serverError': 'Server Error',
  'someMiniprogramLinked': 'Some of the mini-programs are linked',
  'myDiscounts': 'My discounts',
  'myPoints': 'My points',
  'recommendationFromFriends': 'Recommendation from friends',
  'tabBarHome': 'Home',
  'tabBarMine': 'Me',
  'tabBarActivity': 'Activity',
  'tabBarMerchantActivity': 'Activity',
  'tabBarMerchant': 'mall',
  'error': 'Error',
  'holidayGiftPackage': 'Holiday gift package',
  'membershipDiscount': 'Membership discount',
  'pointsReward': 'Points reward',
  'commemorativeGifts': 'Commemorative gifts',
  'unknown': 'Unknown',
  'privilegePointsDesc': 'The more points you get, the more you get a good deal for a gift',
  'privilegeGiftDesc': 'Each year\'s birthday and anniversary are given a good gift of the corresponding level',
  'unRegisteredHanlderBtnText': 'Click on the type button below to become a free member and experience the full functionality',
  'applicableTime': 'Applicable time',
  'applicablePeriod': 'Applicable period',
  'scopeOfApplication': 'Applicable scope',
  'reservationInformation': 'Reservation information',
  'whetherItCanBeStacked': 'Whether it can be stacked',
  'canBeStacked': 'It can be stacked',
  'cannotBeStacked': 'It cannot be stacked',
  'whetherItCanBeShared': 'Whether it can be shared',
  'whetherItCanBeTakenOut': 'Whether it can be take out',
  'eatInOrTakeoutText': 'All food takeaways are available, packing fees please consult the merchant',
  'onlyUseEatIn': 'For meals only, not take out',
  'canBeTakenOut': 'It can be take out',
  'cannotBeTakenOut': 'It cannot be take out',
  'takeawayExclusive': 'Takeaway exclusive',
  'availableBothEatInAndTakeout': 'Both eat in and takeaway are available',
  'eatIn': 'Eat in',
  'payFailedError': 'If payment has failed, please contact the merchant for a refund if the payment has been withheld',
  'businessGroupConfigError': 'Business Settings Error',
  'miniprogramIsDisabled': 'Merchants do not enable mini-programs',
  'free': 'Free',
  'ruleReminder': 'Rule reminders',
  'pleaseAskMerchant': 'Please consult the merchant',
  'usedRewards': 'Rewards used',
  'activityOfflineAndAppointDinnerOver': 'Activities offline',
  'appointSuccessfullyAndWaitForUseReward': 'The meal has been made successful, to be used for reward',
  'waitingToJoin': 'Waiting to join',
  'orderFailedOrOverduePleaseTryAgain': 'Order failed or has expired, please try again',
  'bigRedPocketMoney': 'Big red pocket money',
  'consumeSuccessfully': 'Consume successfully',
  'receivedAndWithxxValidityPeriod': 'Picked up! There\'s a {amount} days validity period.～',
  'friendReceived': 'Friend received',
  'rewardExpired': 'Reward expired～',
  'rewardHasxxValidityPeriod': 'Reward is still valid for 5 days, go and notify your friend to use it.',
  'shopName': 'Shop name',
  'phone': 'Phone number',
  'address': 'Address',
  'tapToCall': 'Click to call',
  'noLocationAutorizationTips': 'You do not have permission to obtain geographic bit information, please go to authorize',
  'noInstructions': 'No instructions',
  'validTime': 'Valid time',
  'validForever': 'Permanent',
  'halfNaturalYear': 'Half natural year',
  'oneNaturalYear': 'One natural year',
  'twoNaturalYear': 'Two natural year',
  'goodsInstruction': 'Goods instruction',
  'pointsInfoGoodsInstructionDetail': 'When the linking is complete, the points will automatically enter the user\'s account, and the user can redeem, redeem, redeem, etc.',
  'amountInfoGoodsInstructionDetail': 'When the linking is complete, the stored value will automatically enter the user\'s account and the user can consume it using the stored value',
  'usageRule': 'Usage rule',
  'giftDetails': 'Gift details',
  'unitFen': 'cent',
  'unitYuan': 'RMB',
  'actuallyPaid': 'Actually paid',
  'sendToYourself': 'For yourself',
  'sendToFriend': 'For friend',
  'viewCard': 'View card',
  'redeemBenefitsWithPoints': 'Redeem your benefits with points',
  'powerByZaihui': 'Power by Zaihui',
  'ruleDetails': 'Rule details',
  'sendGiftCard': 'Give gift card',
  'giftCardDetail': 'Gift card detail',
  'heFromStar': 'The people from mars',
  'giftCardSentSuccessfully': 'Gift card sent successfully',
  'directUseCoupon': 'Type code to use',
  'scanCodeToUseCoupon': 'Scan QR code to use',
  'couponTypeGoods': 'Item coupon',
  'couponTypeVoucher': 'Cash coupon',
  'couponTypeDiscount': 'Discount coupon',
  'couponTypeReduction': 'Immediate deductive coupon',
  'couponTypeOthers': 'Other coupon',
  'redEnDialogCantTitle': 'This event is for new users only',
  'redEnDialogCantContent': 'You can also invite friends to open the red pocket',
  'redEnDialogCantPosText': 'Launch an event, open a red envelope with a friend',
  'redEnDIalogCantNegText': 'Go to the homepage for other events',
  'redEnDialogFailTitle': 'Sorry',
  'redEnDialogFailContent': 'You did not gather your friends in the required time',
  'redEnDialogFailPosText': 'Relaunch promotions',
  'redEnDialogFailNegText': 'Give up the red envelope, go to the homepage for other events',
  'redEnDialogAllTitle': 'You\'re late, your friend has finished splitting the red envelope',
  'redEnDialogAllContent': 'You can also summon new friends to share cash red pocket money',
  'redEnDialogAllPosText': 'Launch an event, open a red envelope with a friend',
  'redEnDialogAllNegText': 'Go to the homepage for other events',
  'redEnDialogEndTitle': 'This event has ended',
  'redEnDialogEndContent': 'Discover other promotions',
  'redEnDialogEndPosText': 'Go to the homepage for other events',
  'appointDinnerProgressUndeway': 'Inviting',
  'appointDinnerProgressFinished': 'Over',
  'appointDinnerProgressReady': 'Ready for meal',
  'appointDinnerProgressOffline': 'Offline',
  'activityOffline': 'The event is offline and cannot be joined',
  'tierEarnBtnText': 'Earn',
  'selectCardCover': 'Select card cover',
  'selected': 'Selected',
  'giftCardUnitPackage': 'package',
  'giftCardUnitSingle': '',
  'myAccountLevel': 'My Account Level',
  'levelChangeRecord': 'Level change record',
  'linkWechatAccountSetting': 'Linked wechat settings',
  'advertorialListPageTitle': 'Shop news',
  'prepayBalance': 'Balance',
  'businessDistrictSettings': 'Business districts',
  'citySettings': 'City settings',
  'nickNameSettings': 'Nickname settings',
  'phoneSettings': 'Phone Number settings',
  'memberPrepay': 'Balance',
  'prepayPasswordSettings': 'Balance transaction password settings',
  'occupationSettings': 'Career setting',
  'profile': 'Profile',
  'redeemCoupon': 'Use coupon',
  'login': 'Login',
  'transactionHistory': 'Transaction history',
  'ongoingPromotions': 'Ongoing promotions',
  'promotionCenter': 'Promotion center',
  'linkGiftCard': 'Link gift card',
  'myTeam': 'My team',
  'promoteToMakeMoney': 'Promote to make money',
  'campainTypeFirstTime': 'Membership welcome pack',
  'campainTypeAtRisk': 'Shop reward',
  'campainTypeLapsed': 'Shop reward',
  'campainTypeRepeat': 'Shop reward',
  'campainTypeRem': 'Lei Mu Coupon',
  'campainTypeN': 'Membership benefits',
  'campainTypeR': 'Membership benefits',
  'campainTypeSR': 'Membership benefits',
  'campainTypeSSR': 'Membership benefits',
  'campainTypeBirthday': 'Membership birthday gift',
  'campainTypeAnniversary': 'Membership anniversary gift',
  'campainTypeMonthly': 'Membership monthly commemorative gift',
  'campainTypeQuarterly': 'Membership quarterly commemorative gift',
  'campainTypeManual': 'Shop reward',
  'campainTypeForHost': 'Activity reward',
  'campainTypeForGuest': 'Activity reward',
  'campainTypeAdvertorialBurden': 'Activity reward',
  'campainTypeAdvertorialNewbie': 'Activity reward',
  'campainTypeAdvertorial': 'Activity reward',
  'campainTypeHuiLife': 'Shop reward',
  'campainTypeWaiterComment': 'Shop reward',
  'campainTypeGiftCard': 'Purchased gift card',
  'campainTypePrepay': 'Top up rebate',
  'campainTypePayRebate': 'Consumption rebate',
  'campainTypeMerchandise': 'Item',
  'campainTypeMilestone': 'Activity reward',
  'campainTypePointS': 'Activity reward',
  'campainTypePartner': 'Shop reward',
  'campainTypeECard': 'Purchased gift card',
  'campainTypePooling': 'Activity reward',
  'campainTypeAutoMarketing': 'Activity reward',
  'campainTypeADPutting': 'Shop reward',
  'campainTypeRedPackRebate': 'Red pocket rebate',
  'campainTypeLottery': 'Activity reward',
  'campainTypeMerchandiseTier': 'Consumption rebate',
  'campainTypeCheckIn': 'Activity reward',
  'campainTypeDailyLottery': 'Activity reward',
  'availableAllShops': 'Available in all shops',
  'makeMoneyNotAvailable': 'This feature is not available yet',
  'giftCardDetailWishText': 'Write down what you want to say to him/her, no more than 100 words',
  'sendCardDocItem1': 'Each gift card can be given to friends or yourself',
  'sendCardDocItem2': 'If you give it to a friend, the friend clicks on the gift card link I share, which is automatically accepted and linked to the gift card, and the friend can view the card in "My Gift Card"',
  'sendCardDocItem3': 'If you give it to yourself, click "Give it to yourself" to automatically link my account',
  'sendCardDocItem4': 'Each gift card can only be linked once, and if it is sent to multiple friends at the same time, the system will automatically link the friend who clicked the link first',
  'sendCardDocItem5': 'Undelivered cards can be found in Gift Cards - Purchased Gift Cards',
  'useCouponPassword': 'Password to use coupon',
  'cardSentInfo': 'Gifts in card are placed in "My Coupons/Points/Balance"',
  'upgradeTo': 'Upgrade to ',
  'downgradeTo': 'Downgrade to ',
  'entryTopLevelDesc': 'Congratulations, you\'re already a top member',
  'langSelectTips': 'After switching languages, you need to manually close the mini-program and reopen it to take effect',
  'langBtnText': 'Language',
  'continueToBuy': 'Continue to buy',
  'redenRuleItem1': '1. Merchant give a big red envelope, the leader of the group call N members together to rob, piece together enough to piece together the number of can be disassembled red envelopes, red envelope amount random points',
  'redenRuleItem2': '2. Each participant can only tear down the red envelope once, the leader of the group can initiate a number of groups, tear down multiple red envelopes',
  'redenRuleItem3': '3. The leader of the group needs to be successful in the current red envelope removal or after the failure of the overdue, before the new mass, remove a red envelope',
  'redenRuleItem4': '4. Red-bag removal activities are valid for 24 hours, 24 hours without a group to fail',
  'redenRuleItem5': '5. 5. The sum of the cash vouchers obtained by each person in the red envelope shall not exceed 1000 Yuan, and the final interpretation shall be vested in the merchant',
  'advertorialGetCouponBtnText': 'Get coupon now',
  'JoinMembershipToGetCoupon': 'Join a membership to get coupon',
  'hasExpired': 'Expired',
  'offlineText1': 'Service unavailable',
  'offlineText2': 'Please go to the merchant Wechat official account to view more',
  'storehomeOffline': 'Storehome has offline',
  'allProducts': 'All Products',
  'verified': 'certified',
  'discountPay': 'Discount Pay',
  'promoteMoney': 'Promote Money',
  'memberStore': 'Member Store',
  'activityCenter': 'Activity Center',
  'giftCard': 'Gift Card',
  'businessInformation': 'Business Information',
  'specialActivity': 'Special Activity',
  'serviceUnavailable': 'Service unavailable',
  'haveAgreed': 'I have agreed to',
  'membershipAgreement': 'the membership agreement',
  'userPrivacyPolicy': 'privacy policy',
  'record': 'Record',
  'signInToGetGift': 'Sign in to get gift',
  'signInGifts': 'Sign in gifts',
  'signInToGetGiftEveryDay': 'Sign in to get gift every day',
  'signInToGetGiftBubble': 'Sign in daily to get gift',
  'signedAwardEveryday': 'Signed award every day',
  'consecutiveSignedAward': 'Consecutive signed (extra award)',
  'transferredToMyProperty': 'The balance has been transferred to my property',
  'signInTomorrowAgain': 'Signed successfully,  come back tomorrow',
  'signInPolite': 'Sign in to get gift',
  'noRewardInfo': 'You don\'t have a reward yet. Just sign in and get it',
  'today': 'Today',
  'mon': 'Mon',
  'tue': 'Tue',
  'wed': 'Wed',
  'thurs': 'Thu',
  'fri': 'Fri',
  'sat': 'Sat',
  'sun': 'Sun',
  'lotterySoonBegin': 'The activity is coming soon',
  'lotteryForFree': 'Draw a lottery for free',
  'lotteryShareFriend': 'Share with friends and get one more chance',
  'lotteryShareGroup': 'Share to Wechat group chat and get one more chance',
  'lotteryChanceOut': 'Chances have been used up, come back next time',
  'lotteryBtnOver': 'This event has ended',
  'lotteryFreeTitle': 'Lottery free',
  'lotteryRedPkg': 'Wechat red packet',
  'lotteryMyRecord': 'My winning record',
  'noPhone': 'Merchant has not set contact information',
  'lotteryEntryTitle': 'Daily lottery draw',
  'lotteryEntryDesc': 'Invite friends to draw a lottery',
  'discountText': '% Off',
  'activityCamp': 'Event Camp',
  'activityCampSuffix': '',
  'unitPoint': 'point',

  // 动态拼接模版
  'discountNum': '{amount}',
  'lotteryFreeGet': 'Free prize draw {content}',
  'lotteryGetRedPkg': '{number} yuan red packet',
  'lotteryRedAvaliable': 'can be used when consuming over {number} yuan',
  'lotteryMissContent': 'You almost win the lottery {date}',
  'lotteryGotVirtualContent': 'You got lottery reward {content}',
  'lotteryGotActuralContent': 'You got {content}, redeem code {code}. You will be contacted or you can pick up in store',
  'signInGetGiftAgain': 'Sign in for another {day} days to get extra gift',
  'extraReward': 'Congratulations, you got an extra reward {text}',
  'twoSignInReward': 'Congratulations, you got an reward {oneText}, extra reward {twoText}',
  '优惠券使用门店': 'Use shop: {name}',
  '优惠券使用时间': 'Use in: {time}',
  '优惠券可用时间范围': 'Available from {start} to {end}',
  'expiredXX': 'Expired: {time}',
  'usexx': 'Use {name}',
  'getxx': 'Gain {name}',
  'xxAvailable': 'Available in {name}',
  'xxPointsDeductiblexxRMB': '{points} points deductible ¥{amount}',
  'prepayxxRMB': 'Prepay ¥{amount}',
  'pointsxx': 'Points {amount}',
  'xxCoupons': '{amount} coupons',
  'xxPoints': '{amount} Points',
  'xxRMBBounty': '¥{amount} reward',
  'xxPercentBouns': 'Return of {amount}% reward',
  'xxRMBCash': '¥{amount} in cash',
  'refundRuleText2': 'Refund amount is not available on the same day',
  'upToxxRMBforTheDay': 'Up to ¥{amount} for the day',
  'benefitsRuleText1': 'Return {amount}% of the usage amount to the stored balance when spending with the top-up amount',
  'availablexxToxx': 'Expiration date: {name}',
  'rechargeSuccessTipText': '{amount} cash has been put into my balance',
  'myxx': 'total {name}',
  'givexxPoints': 'Give away {amount} points',
  'legacyUpgradeRulePaymentTimesContent': 'Cumulative consumption reached {amount} times, upgrade to {levelTitle}', // ?
  'legacyUpgradeRuleLifePointContent': 'Cumulative points reached {amount}, upgrade to {levelTitle}', // ?
  'legacyUpgradeRulePrepayAmountContent': 'Cumulative balance reached ¥{amount}, upgrade to {levelTitle}', // ?
  'upgradeRuleContent': 'The current level is {currentLevelTitle}, accumulated {total} in {days} days, upgrade to {newLevelTitle}',
  'downgradeRuleContent': '{days} days in a row did not come to the shop consumption, downgrade to {newLevelTitle}',
  'levelChangeNoticeContent': 'Your membership level changes at {date} due to merchant adjustment of level rules',
  'levelUpgradeTip': 'Congratulations, you\'re already {name}',
  'inxxdays': 'In {amount} days',
  'upgradePaymentTimesRequiredContent': '{limit} spend more {difference} times to upgrade to {name}', // ?
  'upgradePrepayAmountRequiredContent': '{limit} another ¥{difference} be top up to upgrade to {name}', // ?
  'upgradeLifePointRequiredContent': 'Get more {difference} points {limit} can be upgraded to {name}',
  'saveBirthdayReconfirmContent': 'Once the birthday is completed, it can\'t be changed, are you sure your birthday is {date}?',
  'linkGiftCardSuccessContent': 'Gift card {name} has been linked successfully, go to use it',
  'unlockAfterUpgradeContent': 'unlock {name} after upgrade',
  'xxAwayFromMe': '{amount} away from me',
  'startToEnd': '{start} - {end}',
  'xxDiscount': '{amount}% off',
  'abountxxRMB': 'About ¥{amount}',
  'xxDiscountForMember': '{amount}% discount for member',
  'xxXPointsReward': '{amount}x points reward',
  'enjoyXXDiscount': 'Enjoy a {amount}% discount',
  'privilegePointsMultiplierDesc': 'Enjoy {amount}x of spending gift',
  'xxRMB': '¥{amount}',
  'xxNoDiscount': '{name} does not participate in the offer',
  'appointStillNeedxxPeopleText': '{amount} person can get the discount and continue to invite friends',
  'hasSuccessfullyUsedxx': 'Has successfully used {name}',
  'entryLevelLifePointContent': 'Get more {amount} points to upgrade to {levelTitle}',
  'entryLevelPrepayAmountContent': 'Top up more ¥{amount} to upgrade to {levelTitle}',
  'entryLevelPaymentTimesContent': 'Spend {amount} more times to upgrade to {levelTitle}',
  'redEnShareMessageContent': 'I\'m at {name}, come and grab the cash red envelope with me！',
  'couponRelativeValidDateWithDelayText': 'Effective {daysDelay} days after receiving the coupon and available within {daysValid} days(the day receiving the coupon is the first day)',
  'couponRelativeValidDateWithoutDelayText': 'Available within {daysValid} days after receiving the coupon',
}
